name: build and deploy to vercel

on:
  pull_request:
    branches:
      - main
  pull_request_target:

env:
  FOUNDRY_PROFILE: ci

permissions:
  pull-requests: write
  deployments: write

jobs:
  build:
    strategy:
      fail-fast: true

    name: MUD project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: production or not
        id: prod_or_not
        run: |
          if [ "$REF" == 'refs/heads/main' ]
          then
              echo "vercel-args=--prod" >> $GITHUB_OUTPUT
          else
              echo "vercel-args=" >> $GITHUB_OUTPUT
          fi
        env:
          REF: ${{ github.ref }}

      - name: Vercel Action
        uses: amondnet/vercel-action@v25

        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: ${{ steps.prod_or_not.outputs.vercel-args }}
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./packages/client/dist
          scope: ${{secrets.TEAM_SLUG}}
